ALTER TABLE "Job" ADD COLUMN "embeddingRole" JSONB;
ALTER TABLE "Job" ADD COLUMN "embeddingSkills" JSONB;
ALTER TABLE "Job" ADD COLUMN "embeddingDomain" JSONB;
ALTER TABLE "Job" ADD COLUMN "embeddingVersion" TEXT;

-- Existing full vectors remain usable as a temporary fallback while the hybrid
-- role/skills/domain vectors are regenerated by the embedding queue.
UPDATE "Job"
SET "embeddingStatus" = 'pending',
    "embeddingAttempts" = 0,
    "embeddingNextAttemptAt" = CURRENT_TIMESTAMP,
    "embeddingError" = NULL,
    "embeddingVersion" = NULL
WHERE "active" = true;

CREATE INDEX "Job_embeddingVersion_idx" ON "Job"("embeddingVersion");
